<a href="https://colab.research.google.com/github/KucharskiR/data-science/blob/main/Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=12, suppress=True, linewidth=150)
pd.options.display.float_format = '{:.6f}'.format
# sns.set()   <--- seaborn
print(np.__version__)

1.25.2


In [ ]:
close = 75
vwamp = 70

In [3]:
data = np.array([75,70,74,73,50,49.7,70,75,80,80])

In [4]:
data = np.reshape(data,(-1,2))
data

array([[75. , 70. ],
       [74. , 73. ],
       [50. , 49.7],
       [70. , 75. ],
       [80. , 80. ]])

In [5]:
# df = pd.DataFrame(my_array, columns=['Column_A', 'Column_B', 'Column_C'])
df = pd.DataFrame(data, columns=['Close', 'VWAP'])
df

Close      VWAP
0 75.000000 70.000000
1 74.000000 73.000000
2 50.000000 49.700000
3 70.000000 75.000000
4 80.000000 80.000000

In [7]:
for i in range(len(df)):
  multi = 5
  close = df.iloc[i,0]
  vwap = df.iloc[i,1]
  if(vwap<close):
    vwap /= close
    vwap-= 1
    vwap *= multi
  else:
    vwap = close/vwap
    vwap-= 1
    vwap *= (-1)*multi

  print(vwap)


-0.33333333333333326
-0.06756756756756743
-0.02999999999999947
0.33333333333333326
-0.0


In [ ]:
trendf = np.array([0,0.01,0.254,0.5,0.77,0.99,1])
trendDf = pd.DataFrame(trendf, columns=['Trend_Filter'])
trendDf

Trend_Filter
0         0.000
1         0.010
2         0.254
3         0.500
4         0.770
5         0.990
6         1.000

In [ ]:
for i in range(len(trendDf)):
  value = trendDf.iloc[i,0]
  value = (2*value - 1)/1
  print(value)

-1.0
-0.98
-0.492
0.0
0.54
0.98
1.0


### Heiken

In [ ]:
h = np.array([75,75.1,75.1,75,79,79.3,79.3,79])
h = h.reshape(-1,2)
h

array([[75. , 75.1],
       [75.1, 75. ],
       [79. , 79.3],
       [79.3, 79. ]])

In [ ]:
hdf = pd.DataFrame(h, columns=['H1', 'H2'])
hdf

H1        H2
0 75.000000 75.100000
1 75.100000 75.000000
2 79.000000 79.300000
3 79.300000 79.000000

In [ ]:
for i in range(len(hdf)):
  h1 = hdf.iloc[i,0]
  h2 = hdf.iloc[i,1]
  if(h1 < h2):
    heikenResult = (h1 / h2) -1
    heikenResult *= 100
  else:
    heikenResult = (h2 / h1) -1
    heikenResult *= -100

  print(heikenResult)

-0.13315579227695107
0.13315579227695107
-0.3783102143757877
0.3783102143757877


In [7]:
data = np.array([380000,375000,55000,56000,56000,55000, -56000,-55000, -55000,-56000,3000000,2000000])
data

array([ 380000,  375000,   55000,   56000,   56000,   55000,  -56000,  -55000,  -55000,  -56000, 3000000, 2000000])

In [8]:
data = data.reshape(-1,2)
data

array([[ 380000,  375000],
       [  55000,   56000],
       [  56000,   55000],
       [ -56000,  -55000],
       [ -55000,  -56000],
       [3000000, 2000000]])

In [9]:
obvDf = pd.DataFrame(data, columns=['MA', 'OBV'])
obvDf

MA      OBV
0   380000   375000
1    55000    56000
2    56000    55000
3   -56000   -55000
4   -55000   -56000
5  3000000  2000000

In [10]:
for i in range(len(obvDf)):
  ma = obvDf.iloc[i,0]
  obv = obvDf.iloc[i,1]
  if(obv > 0):
     if(obv < ma):
      out = (ma / obv) -1
      out *= -5
     else:
      out = (obv / ma) -1
      out *= 5
  else:
    if(obv < ma):
      out = (obv / ma) -1
      out *= -5
    else:
      out = (ma / obv) -1
      out *= 5

  print(out)

-0.0666666666666671
0.09090909090909038
-0.09090909090909038
0.09090909090909038
-0.09090909090909038
-2.5


### Wycięgnięcie ostatniej kolumny

In [ ]:
import numpy as np

# Przykładowa tablica 3-elementowa
arr = np.array([1,0,5.0,1,0,5.1,1,0,5.2])
arr = arr.reshape(-1,3)
arr

array([[1. , 0. , 5. ],
       [1. , 0. , 5.1],
       [1. , 0. , 5.2]])

In [ ]:
# Wyciąganie dwóch pierwszych kolumn
col = arr[:, 0:2]
col

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
d = pd.DataFrame(data=col,columns=['Predict_B','Predict_S'])
d

Predict_B  Predict_S
0        1.0        0.0
1        1.0        0.0
2        1.0        0.0

In [ ]:
# Wyciąganie ostatniej kolumny do osobnej tablicy
lastCol = arr[:, 2:]
lastCol

array([[5. ],
       [5.1],
       [5.2]])

In [ ]:
d = pd.DataFrame(data=lastCol,columns=['Close'])
d

Close
0    5.0
1    5.1
2    5.2

###Klasyfikacja (classification)

Binary Classification
Use a threshold to select the probabilities that will determine class 0 or 1



> `np.where(y_pred > threshold, 1,0)`



For example use a threshold of 0.5


Mutli-class Classification
Select the class with the highest probability

> `np.argmax(predictions, axis=1)`

Multi-label Classification
Where you can have multiple output classes per example, use a threshold to select which labels apply.


> `y_pred = model.predict(x, axis=1)`

[i for i,prob in enumerate(y_pred) if prob > 0.5]

###Wykresy

In [ ]:
import plotly.express as px
import pandas as pd

# Przykładowe dane (zastąp je danymi, które masz)
data = {
    'Kolumna1': [1, 0, 1, 0, 1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1],
    'Kolumna2': [0, 1, 1, 0, 0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],
    'Kolumna3': [10, 20, 15, 25, 30,31,32,32.5,33,32,35,36,36,35.5,35,36,37,38,38.5,39,39.2]
}
df = pd.DataFrame(data)
df

Kolumna1  Kolumna2  Kolumna3
0          1         0      10.0
1          0         1      20.0
2          1         1      15.0
3          0         0      25.0
4          1         0      30.0
5          1         0      31.0
6          1         0      32.0
7          1         0      32.5
8          1         0      33.0
9          1         0      32.0
10         1         0      35.0
11         1         0      36.0
12         0         1      36.0
13         0         1      35.5
14         0         1      35.0
15         1         0      36.0
16         1         0      37.0
17         1         0      38.0
18         1         0      38.5
19         1         0      39.0
20         1         0      39.2

In [ ]:
import plotly.graph_objects as go
import pandas as pd# Tworzenie wykresu liniowego

# Tworzenie wykresu liniowego
fig = go.Figure()

# Dodawanie linii do wykresu
for i in range(1, len(df)):
    color = 'green' if df.at[i, 'Kolumna1'] == 1 else 'red'
    fig.add_trace(go.Scatter(x=[i-1, i], y=[df.at[i-1, 'Kolumna3'], df.at[i, 'Kolumna3']], line=dict(color=color), showlegend=False))

# Ustawienia osi i tytuł
fig.update_layout(
    xaxis_title='Indeks',
    yaxis_title='Close',
    title='Wykres liniowy z kolorami'
)

# Wyświetlanie wykresu
fig.show()

In [ ]:
import plotly.graph_objects as go
import pandas as pd

# Przykładowe dane (zastąp je danymi, które masz)
data = {
    'Kolumna1': [1, 0, 1, 0, 1,1,1,1],
    'Kolumna2': [0, 1, 1, 0, 0,0,0,0],
    'Open': [100, 105, 98, 102, 110,111,112,112],
    'High': [110, 112, 105, 108, 115,116,117,116],
    'Low': [95, 100, 97, 98, 105,104,103,103],
    'Close': [105, 108, 100, 105, 112,112,113,113.2]
}

df = pd.DataFrame(data)
df

Kolumna1  Kolumna2  Open  High  Low  Close
0         1         0   100   110   95  105.0
1         0         1   105   112  100  108.0
2         1         1    98   105   97  100.0
3         0         0   102   108   98  105.0
4         1         0   110   115  105  112.0
5         1         0   111   116  104  112.0
6         1         0   112   117  103  113.0
7         1         0   112   116  103  113.2

In [ ]:
# Tworzenie wykresu słupkowego (Bar)
fig = go.Figure()

# Dodawanie słupków OHLC do wykresu
for i in range(len(df)):
    color = 'green' if df.at[i, 'Kolumna1'] == 1 else 'red'
    fig.add_trace(go.Ohlc(x=[i], open=[df.at[i, 'Open']], high=[df.at[i, 'High']], low=[df.at[i, 'Low']], close=[df.at[i, 'Close']],
                          increasing_line_color=color, decreasing_line_color=color, showlegend=False))

# Ustawienia osi i tytuł
fig.update_layout(
    xaxis_title='Indeks',
    yaxis_title='Close',
    title='Wykres słupkowy z kolorami'
)

# Wyświetlanie wykresu
fig.show()